# Generated by Django 4.2.3 on 2024-07-11 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gasto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_correspondiente', models.DateField()),
                ('mes', models.CharField(editable=False, max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(4, 6, 27, 539504), editable=False),
        ),
    ]
