# Generated by Django 4.2.3 on 2024-09-04 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0002_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(6, 51, 54, 884357), editable=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
