# Generated by Django 4.2.3 on 2023-08-27 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0003_jornada_huerto_jornada_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='huerto',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.huerto'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='lote',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.lote'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='sector',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.sector'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(13, 23, 10, 973336), editable=False),
        ),
    ]
