# Generated by Django 4.2.3 on 2024-07-29 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0004_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumiditySoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humiditysoil', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 31, 19, 72146), editable=False),
        ),
    ]
