# Generated by Django 4.2.3 on 2023-08-27 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0007_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 13, 26, 497420), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='huerto',
            field=models.ForeignKey(default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.huerto'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='lote',
            field=models.ForeignKey(default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.lote'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='sector',
            field=models.ForeignKey(default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.sector'),
        ),
    ]
