# Generated by Django 4.2.3 on 2023-08-27 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0008_alter_procesos_hora_creacion_alter_procesos_huerto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 17, 10, 675745), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='huerto',
            field=models.ForeignKey(blank=True, default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.huerto'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='lote',
            field=models.ForeignKey(blank=True, default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.lote'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='sector',
            field=models.ForeignKey(blank=True, default='sin especificar', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.sector'),
        ),
    ]
