# Generated by Django 4.2.3 on 2024-07-24 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0009_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(3, 18, 13, 241206), editable=False),
        ),
    ]
