# Generated by Django 4.2.3 on 2023-09-08 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0010_alter_procesos_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(23, 32, 13, 542588), editable=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, default='Sin Fecha Termino', null=True),
        ),
    ]
