# Generated by Django 4.2.3 on 2023-09-08 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0015_alter_jornada_cobro_tarea_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(1, 15, 1, 841490), editable=False),
        ),
    ]
