# Generated by Django 4.2.3 on 2023-09-08 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0016_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(1, 25, 17, 237175), editable=False),
        ),
    ]
