# Generated by Django 4.2.3 on 2023-09-08 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0018_alter_jornada_cobro_tarea_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(1, 45, 32, 532928), editable=False),
        ),
    ]
