# Generated by Django 4.2.3 on 2023-09-08 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0020_alter_jornada_cobro_tarea_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(1, 50, 53, 402491), editable=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cobro',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
