# Generated by Django 4.2.3 on 2023-09-08 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0021_alter_procesos_hora_creacion_alter_trabajador_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('Por Realizar', 'Por Realizar'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Por Realizar', max_length=15),
        ),
        migrations.AddField(
            model_name='jornada',
            name='gasto_extra_1',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='gasto_extra_2',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='gasto_extra_3',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='nombre_extra_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='nombre_extra_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='nombre_extra_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='total_gasto_jornada',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_2',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 54, 25, 497407), editable=False),
        ),
    ]
