# Generated by Django 4.2.3 on 2023-09-11 03:33

import agrosmartiotweb.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0022_jornada_estado_jornada_gasto_extra_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='total_gasto_jornada',
            field=models.IntegerField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(0, 33, 3, 381993), editable=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=12, null=True, validators=[agrosmartiotweb.models.validate_rut]),
        ),
    ]
