# Generated by Django 4.2.3 on 2023-09-11 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0023_alter_jornada_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(0, 38, 36, 910191), editable=False),
        ),
    ]
