# Generated by Django 4.2.3 on 2023-09-12 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0024_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='detalle_gasto_total_tareas',
            field=models.IntegerField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='detalle_gastos_total_extras',
            field=models.IntegerField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(22, 40, 16, 383648), editable=False),
        ),
    ]
