# Generated by Django 4.2.3 on 2023-09-23 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0025_jornada_detalle_gasto_total_tareas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='nombre_jornada',
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 14, 56, 361142), editable=False),
        ),
    ]
