# Generated by Django 4.2.3 on 2023-09-23 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0026_remove_jornada_nombre_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='huerto',
            field=models.ForeignKey(blank=True, choices=[('sin_asignar', 'Sin huerto asignado'), ('todos_sector', 'Todos los huertos del sector')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.huerto'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 31, 24, 132980), editable=False),
        ),
    ]
