# Generated by Django 4.2.3 on 2023-09-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0027_alter_jornada_huerto_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='huerto',
            field=models.CharField(blank=True, choices=[('sin_asignar', 'Sin huerto asignado'), ('todos', 'Todos los huertos de la viña')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='lote',
            field=models.CharField(blank=True, choices=[('sin_asignar', 'Sin lote asignado'), ('todos', 'Todos los lotes del huerto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(12, 10, 11, 493515), editable=False),
        ),
    ]
