# Generated by Django 4.2.3 on 2023-09-24 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0028_alter_jornada_huerto_alter_jornada_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='huerto',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.huerto'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='lote',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.lote'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(12, 10, 57, 358511), editable=False),
        ),
    ]
