# Generated by Django 4.2.3 on 2023-10-14 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0033_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 4, 3, 727181), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 4, 3, 727181), editable=False),
        ),
    ]
