# Generated by Django 4.2.3 on 2023-10-14 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0034_jornada_hora_creacion_alter_procesos_hora_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 10, 28, 442192), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 10, 28, 440200), editable=False),
        ),
    ]
