# Generated by Django 4.2.3 on 2023-10-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0036_jornada_fecha_creacion_alter_jornada_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 13, 43, 328934), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(10, 13, 43, 327936), editable=False),
        ),
    ]
